using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class MoveMouseMini : MonoBehaviour
{
    [SerializeField] private float _moveSpeed = 10f; // Specify the move speed

    public InputMaster PlayerInputMaster; //controls cass generated by unity

    private InputAction _lookAround;
    private Vector2 _moveDirection;

    private void Awake()
    {
        PlayerInputMaster = new InputMaster();

    }

    private void OnEnable()
    {
        _lookAround = PlayerInputMaster.Player.LookAround;
        _lookAround.Enable();
    }

    private void OnDisable()
    {
        _lookAround.Disable();
    }
    void Update()
    {
        _moveDirection = _lookAround.ReadValue<Vector2>();
        Vector3 worldPosition = _moveDirection;
        transform.position += new Vector3(worldPosition.x, worldPosition.y, 0) * Time.deltaTime * _moveSpeed;
    }
}
